const tierData = [
  {
    id: "tier1",
    unlockPrice: 10,
    isUnlocked: true,
    isFilling: false,
    hasManager: false,
    isPerSecond: false,
    name: "Wordpress Website",
    income: 10,
    incomePerSecond: null,
    incomeBase: 10,
    delay: 600,
    investPrice: 50,
    investPriceCoefficient: 1.07,
    investCount: 0,
    milestoneIndex: 0,
    timer: null,
  },
  {
    id: "tier2",
    unlockPrice: 600,
    isUnlocked: false,
    isFilling: false,
    hasManager: false,
    isPerSecond: false,
    name: "Vue.js App",
    income: 600,
    incomePerSecond: null,
    incomeBase: 600,
    delay: 3000,
    investPrice: 600,
    investPriceCoefficient: 1.15,
    investCount: 0,
    milestoneIndex: 0,
    timer: null,
  },
  {
    id: "tier3",
    unlockPrice: 7200,
    isUnlocked: false,
    isFilling: false,
    hasManager: false,
    isPerSecond: false,
    name: "Next.js App",
    income: 5400,
    incomePerSecond: null,
    incomeBase: 5400,
    delay: 6000,
    investPrice: 7200,
    investPriceCoefficient: 1.14,
    investCount: 0,
    milestoneIndex: 0,
    timer: null,
  },
  {
    id: "tier4",
    unlockPrice: 86400,
    isUnlocked: false,
    isFilling: false,
    hasManager: false,
    isPerSecond: false,
    name: "Ruby on Rails App",
    income: 43200,
    incomePerSecond: null,
    incomeBase: 43200,
    delay: 12000,
    investPrice: 86400,
    investPriceCoefficient: 1.13,
    investCount: 0,
    milestoneIndex: 0,
    timer: null,
  },
  {
    id: "tier5",
    unlockPrice: 1036800,
    isUnlocked: false,
    isFilling: false,
    hasManager: false,
    isPerSecond: false,
    name: "Quantum App",
    income: 518400,
    incomePerSecond: null,
    incomeBase: 518400,
    delay: 24000,
    investPrice: 1036800,
    investPriceCoefficient: 1.12,
    investCount: 0,
    milestoneIndex: 0,
    timer: null,
  },
  {
    id: "tier6",
    unlockPrice: 12441600,
    isUnlocked: false,
    isFilling: false,
    hasManager: false,
    isPerSecond: false,
    name: "Unity Game",
    income: 6220800,
    incomePerSecond: null,
    incomeBase: 6220800,
    delay: 96000,
    investPrice: 12441600,
    investPriceCoefficient: 1.11,
    investCount: 0,
    milestoneIndex: 0,
    timer: null,
  },
  {
    id: "tier7",
    unlockPrice: 149299200,
    isUnlocked: false,
    isFilling: false,
    hasManager: false,
    isPerSecond: false,
    name: "Unreal Engine Game",
    income: 74649600,
    incomePerSecond: null,
    incomeBase: 74649600,
    delay: 384000,
    investPrice: 149299200,
    investPriceCoefficient: 1.1,
    investCount: 0,
    milestoneIndex: 0,
    timer: null,
  },
  {
    id: "tier8",
    unlockPrice: 1791590400,
    isUnlocked: false,
    isFilling: false,
    hasManager: false,
    isPerSecond: false,
    name: "CryEngine Game",
    income: 895795200,
    incomePerSecond: null,
    incomeBase: 895795200,
    delay: 1536000,
    investPrice: 1791590400,
    investPriceCoefficient: 1.09,
    investCount: 0,
    milestoneIndex: 0,
    timer: null,
  },
  {
    id: "tier9",
    unlockPrice: 21499084800,
    isUnlocked: false,
    isFilling: false,
    hasManager: false,
    isPerSecond: false,
    name: "Triple A Custom Engine",
    income: 10749542400,
    incomePerSecond: null,
    incomeBase: 10749542400,
    delay: 6144000,
    investPrice: 21499084800,
    investPriceCoefficient: 1.08,
    investCount: 0,
    milestoneIndex: 0,
    timer: null,
  },
];

export default tierData;
