const tierData = [
  {
    id: "tier1",
    unlockPrice: 10,
    isUnlocked: true,
    isFilling: false,
    hasManager: false,
    isPerSecond: false,
    name: "Wordpress Website",
    income: 10,
    incomePerSecond: null,
    incomeBase: 10,
    delay: 600,
    investPrice: 50,
    investPriceCoefficient: 1.07,
    investCount: 0,
    milestoneIndex: 0,
    timer: null,
  },
  {
    id: "tier2",
    unlockPrice: 600,
    isUnlocked: false,
    isFilling: false,
    hasManager: false,
    isPerSecond: false,
    name: "Vue.js App",
    income: 600,
    incomePerSecond: null,
    incomeBase: 600,
    delay: 3000,
    investPrice: 600,
    investPriceCoefficient: 1.15,
    investCount: 0,
    milestoneIndex: 0,
    timer: null,
  },
  {
    id: "tier3",
    unlockPrice: 7200,
    isUnlocked: false,
    isFilling: false,
    hasManager: false,
    isPerSecond: false,
    name: "Next.js App",
    income: 5400,
    incomePerSecond: null,
    incomeBase: 5400,
    delay: 6000,
    investPrice: 7200,
    investPriceCoefficient: 1.14,
    investCount: 0,
    milestoneIndex: 0,
    timer: null,
  },
  {
    id: "tier4",
    unlockPrice: 86400,
    isUnlocked: false,
    isFilling: false,
    hasManager: false,
    isPerSecond: false,
    name: "Ruby on Rails App",
    income: 43200,
    incomePerSecond: null,
    incomeBase: 43200,
    delay: 12000,
    investPrice: 86400,
    investPriceCoefficient: 1.13,
    investCount: 0,
    milestoneIndex: 0,
    timer: null,
  },
  {
    id: "tier5",
    unlockPrice: 1036800,
    isUnlocked: false,
    isFilling: false,
    hasManager: false,
    isPerSecond: false,
    name: "Quantum App",
    income: 518400,
    incomePerSecond: null,
    incomeBase: 518400,
    delay: 24000,
    investPrice: 1036800,
    investPriceCoefficient: 1.12,
    investCount: 0,
    milestoneIndex: 0,
    timer: null,
  },
];

export default tierData;
